### ISSUE TITLE
Class loading error when using pre-launch checker

### ISSUE THREAD

**Issue by UltraBlackLinux** [KosmX/jneedle#45]
Okay so I have just discovered that running this tool alongside some mods breaks *something*:
in my case: ImmediatelyFast, MixinConflictHelper:
```
java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: Provider org.slf4j.jul.JULServiceProvider not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:593) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228) ~[?:?]
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273) ~[?:?]
	at java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309) ~[?:?]
	at java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393) ~[?:?]
	at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:104) ~[slf4j-api-2.0.1.jar:2.0.1]
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:147) ~[slf4j-api-2.0.1.jar:2.0.1]
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:139) ~[slf4j-api-2.0.1.jar:2.0.1]
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:422) ~[slf4j-api-2.0.1.jar:2.0.1]
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:408) ~[slf4j-api-2.0.1.jar:2.0.1]
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357) ~[slf4j-api-2.0.1.jar:2.0.1]
	at net.raphimc.immediatelyfast.ImmediatelyFast.<clinit>(ImmediatelyFast.java:43) ~[transformed-mod-immediatelyfast.i0:0/:?]
...
```
Full log with mod list and stuff: https://mclo.gs/Z3eEjKE

Could you investigate that? Why does it happen?

**Comment by KosmX** [comment]
Please specify the exact jNeedle version you used

**Comment by UltraBlackLinux** [comment]
Jneedle 1.0.1 (current latest version)

It even sais that in the log I sent

**Comment by KosmX** [comment]
Can you please try [this](https://github.com/KosmX/jneedle/releases/tag/1.1.0-local) pre-repease?
> you may need to delete .fabric folder

**Comment by UltraBlackLinux** [comment]
works like a charm and I didn't even have to delete the .fabric folder!

Thanks!

Please add that component thing to the main README. It's considerably easier to set up and understand than all those manual steps
